#!/usr/bin/env bash
set -euo pipefail

rm -rf dist/*

yarn tsn check-version.ts

# build node:
yarn tsc -p tsconfig.json
yarn tsc-alias -p tsconfig.json

# build deno slug:
yarn rollup -c

yarn prettier --write .
